services:
    accounts:
        image: "bghosh482/accounts:s4"
        container_name: "accounts-ms"
        ports:
            - "8080:8080"
        deploy:
            resources:
                limits:
                    memory: 700M
        networks:
            - bghosh482

    loans:
        image: "bghosh482/loans:s4"
        container_name: "loans-ms"
        ports:
            - "8090:8090"
        deploy:
            resources:
                limits:
                    memory: 700M
        networks:
            - bghosh482
    cards:
        image: "bghosh482/cards:s4"
        container_name: "cards-ms"
        ports:
            - "9000:9000"
        deploy:
            resources:
                limits:
                    memory: 700M
        networks:
            - bghosh482
networks:
    bghosh482:
        driver: "bridge"
