spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
       # native:
         # search-locations: "classpath:/config"
        git:
          uri: "git@github.com:bghosh482/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


management:
  endpoints:
    web:
      exposure:
        include: "*" #actuator refresh endpoint


encrypt:
  key: "45@5#5ZXKIEG5%5@5A&3$4%5Z5#33@2"

server:
  port: 8071
